services:
  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    container_name: cbt  # Name of the container
    environment:
      POSTGRES_DB: cbt  # Name of the database to create
      POSTGRES_USER: kossy    # Database user
      POSTGRES_PASSWORD: clear  # Database password
    ports:
      - "4005:5432"  # Map host port 5432 to container port 5432
    # volumes:
    #   - postgres_data: /var/lib/postgresql/data